GET http://localhost:8080/books/1
Accept: application/json

###
POST http://localhost:8080/books/create
Content-Type: application/json

{
  "id": 1,
  "name": "New Book",
  "authorName": "New Author"
}

###

